# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-06 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(null=True)),
                ('counter', models.IntegerField(default=0, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'poke',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=20, null=True)),
                ('last_name', models.TextField(max_length=20, null=True)),
                ('email', models.TextField(max_length=20, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('password', models.TextField(max_length=20, null=True)),
                ('created_at', models.DateField(null=True)),
                ('updated_at', models.DateField(null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='poke',
            name='poked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokedpokes', to='pokes.User'),
        ),
        migrations.AddField(
            model_name='poke',
            name='poker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokerpokes', to='pokes.User'),
        ),
    ]
