# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-06 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pokes', '0002_auto_20180706_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.AddField(
            model_name='user',
            name='confirm',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
