# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-07 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokes', '0003_auto_20180706_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke',
            name='poked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poked_pks', to='pokes.User'),
        ),
        migrations.AlterField(
            model_name='poke',
            name='poker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_pks', to='pokes.User'),
        ),
    ]
